apiVersion: {{ .Values.service.apiVersion }}
kind: Service
metadata:
    name: {{ .Release.Name }}-{{ .Values.service.name }}-{{ .Values.tier }}
    labels:
        app: {{ .Values.appname }}
spec:
    selector:
        app: {{ .Values.appname }}
        tier: {{ .Values.tier }}
        release: {{ .Release.Name }}
    type: {{ .Values.service.type }}
    ports:
      - protocol: TCP
        targetPort: {{ .Values.containerPort }}
        port: {{ .Values.externalPort }}

